import '../styles/globals.css'
import Head from 'next/head'
function MyApp({ Component, pageProps }) {
  return (
    <>
    <Head>
        <title>Metro - Clon</title>
        <meta name="description" content="Generated by create next app" />
        <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js" />
        <link rel="icon" href="/data/logo.svg" />
      </Head>
     <Component {...pageProps} />
    </>
  
  )
}

export default MyApp
