import Head from 'next/head'
import Link from 'next/link'
import BarNav from './components/BarNav'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Metro - Clon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/data/logo.svg" />
      </Head>
      <div>
        <BarNav />
        
      </div>
    </div>
  )
}
